service: blog-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    JWT_SECRET: reallystrongsecret
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - ses:SendEmail
      Resource: "*"

# Lambda functions
functions:
  courses:
    handler: handlers/CoursesHandler.getCourses
    events:
      - http:
          path: courses
          method: get
          cors: true

  articles:
    handler: handlers/ArticlesHandler.getArticles
    events:
      - http:
          path: articles
          method: get
          cors: true

  send-message:
    handler: handlers/MessageHandler.sendMessage
    events:
      - http:
          path: send-message
          method: post
          cors: true

  verify-token:
    handler: handlers/authHandler.verifyToken

  login:
    handler: handlers/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: handlers/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: handlers/AuthHandler.me
    events:
      - http:
          path: me
          method: get
          cors: true
          authorizer: verify-token

# CloudFormation resource template
resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-upload
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
