org: hornyaklaszlo88
app: myapp
service: blog-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - ses:SendEmail
      Resource: "*"

# Lambda functions
functions:
  courses:
    handler: handlers/CoursesHandler.getCourses
    events:
      - http:
          path: courses
          method: get
          cors: true

  articles:
    handler: handlers/ArticlesHandler.getArticles
    events:
      - http:
          path: articles
          method: get
          cors: true

  send-message:
    handler: handlers/MessageHandler.sendMessage
    events:
      - http:
          path: send-message
          method: post
          cors: true

# CloudFormation resource template
resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-upload
